{% set name = "litesata" %}
{% set version = "2025.04" %}
{% set sha256 = "455af49dffcd03509ff44b5ab662d5f9964584590ba90c5984c63f7beb03131f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/enjoy-digital/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-build-isolation --no-deps
  entry_points:
    - litesata_gen = litesata.gen:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - litex ~={{ version }}*
    - liteiclink ~={{ version }}*
    - migen
    - packaging
    - pyyaml

test:
  imports:
    - litesata
  requires:
    - python {{ python_min }}
  commands:
    - litesata_gen --help

about:
  home: https://github.com/enjoy-digital/litesata
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Small footprint and configurable SATA core
  description: Small footprint and configurable SATA core
  dev_url: https://github.com/enjoy-digital/litesata

extra:
  recipe-maintainers:
    - timkpaine
