{% set name = "litesata" %}
{% set version = "2023.12" %}
{% set sha256 = "469570e970a8b4e585d50597afae77a52ace638990eefaea89f9d2ab1bb2ee18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/enjoy-digital/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-build-isolation --no-deps
  entry_points:
    - litesata_gen = litesata.gen:main

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - litex >=2023.08
    - liteiclink >=2023.08
    - migen
    - packaging
    - pyyaml

test:
  imports:
    - litesata
  commands:
    - litesata_gen --help

about:
  home: https://github.com/enjoy-digital/litesata
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Small footprint and configurable SATA core
  description: Small footprint and configurable SATA core
  dev_url: https://github.com/enjoy-digital/litesata

extra:
  recipe-maintainers:
    - timkpaine
