{% set name = "litesata" %}
{% set version = "2024.08" %}
{% set sha256 = "95d66281c7a5980d4f4527eba926e21f295927277b5f12c0be8e5e3d9a23ef65" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/enjoy-digital/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-build-isolation --no-deps
  entry_points:
    - litesata_gen = litesata.gen:main

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7
    - litex ~={{ version }}*
    - liteiclink ~={{ version }}*
    - migen
    - packaging
    - pyyaml

test:
  imports:
    - litesata
  commands:
    - litesata_gen --help

about:
  home: https://github.com/enjoy-digital/litesata
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Small footprint and configurable SATA core
  description: Small footprint and configurable SATA core
  dev_url: https://github.com/enjoy-digital/litesata

extra:
  recipe-maintainers:
    - timkpaine
